name = "ooh-system"
main = "src/index.ts"
compatibility_date = "2025-12-08"

[[d1_databases]]
binding = "DB"
database_name = "ooh-db"
database_id = "79b92724-c85e-401b-a97e-4a77432b3398"
migrations_dir = "../migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "ooh-bucket"

[[kv_namespaces]]
binding = "KV"
id = "d25304aa19f447b384b941c58d43f9d9"

[vars]
ALLOWED_ORIGINS = "*"
